login to both profiles with aws

diff --git a/vaas/scripts/vaasdev b/vaas/scripts/vaasdev
--- a/vaas/scripts/vaasdev
+++ b/vaas/scripts/vaasdev
@@ -598,8 +598,19 @@ function aws_check() {
 }
 
 function aws_login() {
-	aws sso login
-	return $?
+	aws sso login --profile trustnet-dev
+	if [[ $? -ne 0 ]]; then
+		echo -en "ERROR: Failed to login to trustnet-dev.\n\n\n"
+		return 1
+	fi
+
+	aws sso login --profile condor-dev		|| return $?
+	if [[ $? -ne 0 ]]; then
+		echo -en "ERROR: Failed to login to condor-dev.\n\n\n"
+		return 1
+	fi
+
+	return 0
 }
 
 # Call the main function
