Disable the staging context for now because it is failing and I don't care

diff --git a/vaas/scripts/vaasdev b/vaas/scripts/vaasdev
--- a/vaas/scripts/vaasdev
+++ b/vaas/scripts/vaasdev
@@ -562,17 +562,17 @@ function aws_setup() {
 		return 1
 	fi
 
-	echo -en "Configuring staging context..."
-	aws eks update-kubeconfig		\
-		--name staging-ore-vaas		\
-		--profile trustnet-dev		\
-		--region us-west-2			\
-		--alias staging				\
-		--role-arn arn:aws:iam::497086895112:role/eks/staging-ore-vaas-KubernetesDevelopers
-	if [[ $? -ne 0 ]]; then
-		echo -en "ERROR: Failed to configure the staging context.\n\n\n"
-		return 1
-	fi
+#	echo -en "Configuring staging context..."
+#	aws eks update-kubeconfig		\
+#		--name staging-ore-vaas		\
+#		--profile trustnet-dev		\
+#		--region us-west-2			\
+#		--alias staging				\
+#		--role-arn arn:aws:iam::497086895112:role/eks/staging-ore-vaas-KubernetesDevelopers
+#	if [[ $? -ne 0 ]]; then
+#		echo -en "ERROR: Failed to configure the staging context.\n\n\n"
+#		return 1
+#	fi
 
 	echo -en "Configuring devstacks context..."
 	aws eks update-kubeconfig		\
