Disable the devstacks context for now because it is failing and I don't care

diff --git a/vaas/scripts/vaasdev b/vaas/scripts/vaasdev
--- a/vaas/scripts/vaasdev
+++ b/vaas/scripts/vaasdev
@@ -574,17 +574,17 @@ function aws_setup() {
 #		return 1
 #	fi
 
-	echo -en "Configuring devstacks context..."
-	aws eks update-kubeconfig		\
-		--name dev01				\
-		--profile trustnet-dev		\
-		--region us-west-2			\
-		--alias devstacks			\
-		--role-arn arn:aws:iam::497086895112:role/eks/dev01-KubernetesDevelopers
-	if [[ $? -ne 0 ]]; then
-		echo -en "ERROR: Failed to configure the devstacks context.\n\n\n"
-		return 1
-	fi
+#	echo -en "Configuring devstacks context..."
+#	aws eks update-kubeconfig		\
+#		--name dev01				\
+#		--profile trustnet-dev		\
+#		--region us-west-2			\
+#		--alias devstacks			\
+#		--role-arn arn:aws:iam::497086895112:role/eks/dev01-KubernetesDevelopers
+#	if [[ $? -ne 0 ]]; then
+#		echo -en "ERROR: Failed to configure the devstacks context.\n\n\n"
+#		return 1
+#	fi
 
 	echo -en "Setting default k8s context... "
 	kubectl config set-context --current --namespace=$DEVSTACK
