Trying to get condordev working

diff --git a/vaas/scripts/vaasdev b/vaas/scripts/vaasdev
--- a/vaas/scripts/vaasdev
+++ b/vaas/scripts/vaasdev
@@ -538,12 +538,49 @@ function aws_setup() {
 		fi
 	fi
 
-	echo -en "Configuring k8s to use AWS...  "
+	echo -en "Configuring devstacks context..."
 	aws eks update-kubeconfig		\
 		--name dev01				\
-		--region ${AWS_REGION}		\
+		--region us-west-2			\
 		--profile ${AWS_PROFILE}	\
+		--alias devstacks			\
 		--role-arn arn:aws:iam::497086895112:role/eks/dev01-KubernetesDevelopers
+	if [[ $? -ne 0 ]]; then
+		echo -en "ERROR: Failed to configure k8s to use aws.\n\n\n"
+		return 1
+	fi
+
+	echo -en "Configuring staging context..."
+	aws eks update-kubeconfig		\
+		--name staging-ore-vaas		\
+		--region us-west-2			\
+		--profile ${AWS_PROFILE}	\
+		--alias staging				\
+		--role-arn arn:aws:iam::497086895112:role/eks/staging-ore-vaas-KubernetesDevelopers
+	if [[ $? -ne 0 ]]; then
+		echo -en "ERROR: Failed to configure k8s to use aws.\n\n\n"
+		return 1
+	fi
+
+	echo -en "Configuring us-prod-readonly context..."
+	aws eks update-kubeconfig		\
+		--name eksprodcluster		\
+		--region us-east-1			\
+		--profile ${AWS_PROFILE}	\
+		--alias us-prod-readonly	\
+		--role-arn arn:aws:iam::569433869543:role/eks/k8sprod01-KubernetesDevelopers
+	if [[ $? -ne 0 ]]; then
+		echo -en "ERROR: Failed to configure k8s to use aws.\n\n\n"
+		return 1
+	fi
+
+	echo -en "Configuring eu-prod-readonly context..."
+	aws eks update-kubeconfig		\
+		--name prod-fra-vaas		\
+		--region eu-central-1		\
+		--profile ${AWS_PROFILE}	\
+		--alias eu-prod-readonly	\
+		--role-arn arn:aws:iam::569433869543:role/eks/prod-fra-vaas-KubernetesDevelopers
 	if [[ $? -ne 0 ]]; then
 		echo -en "ERROR: Failed to configure k8s to use aws.\n\n\n"
 		return 1
