Okay, update both profiles then

diff --git a/vaas/scripts/vaasdev b/vaas/scripts/vaasdev
--- a/vaas/scripts/vaasdev
+++ b/vaas/scripts/vaasdev
@@ -500,8 +500,8 @@ function aws_setup() {
 		region = ${AWS_REGION}
 
 		[profile trustnet-dev]
-		sso_start_url = https://d-926708eb5a.awsapps.com/start#/
-		sso_region = us-west-2
+		sso_start_url = https://d-906740f971.awsapps.com/start#/
+		sso_region = us-east-1
 		sso_account_id = 497086895112
 		sso_role_name = Vaas.Developer
 		region = ${AWS_REGION}
@@ -574,17 +574,17 @@ function aws_setup() {
 #		return 1
 #	fi
 
-#	echo -en "Configuring devstacks context..."
-#	aws eks update-kubeconfig		\
-#		--name dev01				\
-#		--profile trustnet-dev		\
-#		--region us-west-2			\
-#		--alias devstacks			\
-#		--role-arn arn:aws:iam::497086895112:role/eks/dev01-KubernetesDevelopers
-#	if [[ $? -ne 0 ]]; then
-#		echo -en "ERROR: Failed to configure the devstacks context.\n\n\n"
-#		return 1
-#	fi
+	echo -en "Configuring devstacks context..."
+	aws eks update-kubeconfig		\
+		--name dev01				\
+		--profile trustnet-dev		\
+		--region us-west-2			\
+		--alias devstacks			\
+		--role-arn arn:aws:iam::497086895112:role/eks/dev01-KubernetesDevelopers
+	if [[ $? -ne 0 ]]; then
+		echo -en "ERROR: Failed to configure the devstacks context.\n\n\n"
+		return 1
+	fi
 
 	echo -en "Setting default k8s context... "
 	kubectl config set-context --current --namespace=$DEVSTACK
