More fighting

diff --git a/vaas/scripts/vaasdev b/vaas/scripts/vaasdev
--- a/vaas/scripts/vaasdev
+++ b/vaas/scripts/vaasdev
@@ -513,13 +513,13 @@ function aws_setup() {
 		sso_region = us-east-1
 		sso_account_id = 569433869543
 		sso_role_name = CondorDeveloper
-		region = us-east-1
+		region = ${AWS_REGION}
 		output = json
 		cli_pager=
 
 		[sso-session vaas]
-		sso_start_url = https://d-926708eb5a.awsapps.com/start#/
-		sso_region = ${AWS_REGION}
+		sso_start_url = https://d-906740f971.awsapps.com/start#/
+		sso_region = us-east-1
 		sso_registration_scopes = sso:account:access
 	EOF
 
@@ -562,17 +562,17 @@ function aws_setup() {
 		return 1
 	fi
 
-#	echo -en "Configuring staging context..."
-#	aws eks update-kubeconfig		\
-#		--name staging-ore-vaas		\
-#		--profile trustnet-dev		\
-#		--region us-west-2			\
-#		--alias staging				\
-#		--role-arn arn:aws:iam::497086895112:role/eks/staging-ore-vaas-KubernetesDevelopers
-#	if [[ $? -ne 0 ]]; then
-#		echo -en "ERROR: Failed to configure the staging context.\n\n\n"
-#		return 1
-#	fi
+	echo -en "Configuring staging context..."
+	aws eks update-kubeconfig		\
+		--name staging-ore-vaas		\
+		--profile trustnet-dev		\
+		--region us-west-2			\
+		--alias staging				\
+		--role-arn arn:aws:iam::497086895112:role/eks/staging-ore-vaas-KubernetesDevelopers
+	if [[ $? -ne 0 ]]; then
+		echo -en "ERROR: Failed to configure the staging context.\n\n\n"
+		return 1
+	fi
 
 	echo -en "Configuring devstacks context..."
 	aws eks update-kubeconfig		\
