More tweaks for macOS, and split apart some setup commands to add helpful subcommands like check and login

diff --git a/vaas/scripts/vaasdev b/vaas/scripts/vaasdev
--- a/vaas/scripts/vaasdev
+++ b/vaas/scripts/vaasdev
@@ -88,6 +88,7 @@ function main() {
 		# helm
 		h*|H*)
 			case $SUB in
+				c*)				helm_check			${ARGS[@]}; return $? ;;
 				s*)				helm_setup			${ARGS[@]}; return $? ;;
 				*)				helm_usage			${ARGS[@]}; return $? ;;
 			esac
@@ -97,6 +98,8 @@ function main() {
 		a*|A*)
 			case $SUB in
 				s*)				aws_setup			${ARGS[@]}; return $? ;;
+				l*)				aws_login			${ARGS[@]}; return $? ;;
+				c*)				aws_check			${ARGS[@]}; return $? ;;
 				*)				aws_usage			${ARGS[@]}; return $? ;;
 			esac
 			;;
@@ -159,6 +162,7 @@ function helm_usage() {
 	echo "Usage: vaasdev helm <subcmd>"
 	echo ""
 	echo "  Sub-Commands:"
+	echo "    check         Verify that helm is setup properly"
 	echo "    setup         Run any needed configuration"
 	return 1
 }
@@ -167,6 +171,8 @@ function aws_usage() {
 	echo "Usage: vaasdev aws <subcmd>"
 	echo ""
 	echo "  Sub-Commands:"
+	echo "    check         Verify that AWS is setup properly"
+	echo "    login         Login to AWS"
 	echo "    setup         Run any needed configuration, and login to AWS"
 	return 1
 }
@@ -362,6 +368,8 @@ function docker_setup() {
 	fi
 
 	if ! docker_check ; then
+		echo -en "ERROR: Unable to access venafi images; Does your account have access?\n\n"
+
 		config_reset
 		timeout 15 vaasdev docker stop
 		return 1
@@ -380,13 +388,7 @@ function docker_setup() {
 function docker_check() {
 	# Verify that we can access venafi images
 	docker search venafi | grep venafi\/ >&4 2>&4
-
-	if [[ $? -ne 0 ]]; then
-		echo -en "ERROR: Unable to access venafi images; Does your account have access?\n\n"
-		return 1
-	fi
-
-	return 0
+	return $?
 }
 
 function docker_login() {
@@ -478,6 +480,11 @@ function helm_setup() {
 	return 0
 }
 
+function helm_check() {
+	helm repo list 2>&3 | grep "^venafi\s" >/dev/null
+	return $?
+}
+
 # AWS sub-commands
 ################################################################################
 function aws_setup() {
@@ -509,14 +516,11 @@ function aws_setup() {
 	# Test AWS access; Login again if needed
 	###########################################################
 	echo -en "Checking AWS access...         "
-	aws sts get-caller-identity --profile ${AWS_PROFILE} --no-cli-pager >&3 2>&3
-	if [[ $? -eq 0 ]]; then
+	if aws_check; then
 		echo "Success"
 	else
 		echo "Logging in"
-		aws sso login --profile ${AWS_PROFILE}
-
-		if [[ $? -ne 0 ]]; then
+		if ! aws_login; then
 			echo -en "ERROR: Failed to login to AWS.\n\n\n"
 			config_reset
 			return 1
@@ -542,6 +546,16 @@ function aws_setup() {
 	fi
 
 	return 0
+}
+
+function aws_check() {
+	aws sts get-caller-identity --profile ${AWS_PROFILE} --no-cli-pager >&3 2>&3
+	return $?
+}
+
+function aws_login() {
+	aws sso login --profile ${AWS_PROFILE}
+	return $?
 }
 
 # Call the main function
