Trying to properly support both trustnet-dev and condor-dev

diff --git a/vaas/scripts/vaasdev b/vaas/scripts/vaasdev
--- a/vaas/scripts/vaasdev
+++ b/vaas/scripts/vaasdev
@@ -538,27 +538,15 @@ function aws_setup() {
 		fi
 	fi
 
-	echo -en "Configuring devstacks context..."
+	echo -en "Configuring eu-prod-readonly context..."
 	aws eks update-kubeconfig		\
-		--name dev01				\
-		--profile trustnet-dev		\
-		--region us-west-2			\
-		--alias devstacks			\
-		--role-arn arn:aws:iam::497086895112:role/eks/dev01-KubernetesDevelopers
+		--name prod-fra-vaas		\
+		--profile condor-dev		\
+		--region eu-central-1		\
+		--alias eu-prod-readonly	\
+		--role-arn arn:aws:iam::569433869543:role/eks/prod-fra-vaas-KubernetesDevelopers
 	if [[ $? -ne 0 ]]; then
-		echo -en "ERROR: Failed to configure the devstacks context.\n\n\n"
-		return 1
-	fi
-
-	echo -en "Configuring staging context..."
-	aws eks update-kubeconfig		\
-		--name staging-ore-vaas		\
-		--profile trustnet-dev		\
-		--region us-west-2			\
-		--alias staging				\
-		--role-arn arn:aws:iam::497086895112:role/eks/staging-ore-vaas-KubernetesDevelopers
-	if [[ $? -ne 0 ]]; then
-		echo -en "ERROR: Failed to configure the staging context.\n\n\n"
+		echo -en "ERROR: Failed to configure the eu-prod-readonly context.\n\n\n"
 		return 1
 	fi
 
@@ -574,15 +562,27 @@ function aws_setup() {
 		return 1
 	fi
 
-	echo -en "Configuring eu-prod-readonly context..."
+	echo -en "Configuring staging context..."
 	aws eks update-kubeconfig		\
-		--name prod-fra-vaas		\
-		--profile condor-dev		\
-		--region eu-central-1		\
-		--alias eu-prod-readonly	\
-		--role-arn arn:aws:iam::569433869543:role/eks/prod-fra-vaas-KubernetesDevelopers
+		--name staging-ore-vaas		\
+		--profile trustnet-dev		\
+		--region us-west-2			\
+		--alias staging				\
+		--role-arn arn:aws:iam::497086895112:role/eks/staging-ore-vaas-KubernetesDevelopers
 	if [[ $? -ne 0 ]]; then
-		echo -en "ERROR: Failed to configure the eu-prod-readonly context.\n\n\n"
+		echo -en "ERROR: Failed to configure the staging context.\n\n\n"
+		return 1
+	fi
+
+	echo -en "Configuring devstacks context..."
+	aws eks update-kubeconfig		\
+		--name dev01				\
+		--profile trustnet-dev		\
+		--region us-west-2			\
+		--alias devstacks			\
+		--role-arn arn:aws:iam::497086895112:role/eks/dev01-KubernetesDevelopers
+	if [[ $? -ne 0 ]]; then
+		echo -en "ERROR: Failed to configure the devstacks context.\n\n\n"
 		return 1
 	fi
 
@@ -597,8 +597,19 @@ function aws_setup() {
 }
 
 function aws_check() {
-	aws sts get-caller-identity --no-cli-pager >&3 2>&3
-	return $?
+	aws sts get-caller-identity --no-cli-pager --profile trustnet-dev >&3 2>&3
+	if [[ $? -ne 0 ]]; then
+		echo -en "ERROR: Failed to check trustnet-dev.\n\n\n"
+		return 1
+	fi
+
+	aws sts get-caller-identity --no-cli-pager --profile condor-dev >&3 2>&3
+	if [[ $? -ne 0 ]]; then
+		echo -en "ERROR: Failed to check condor-dev.\n\n\n"
+		return 1
+	fi
+
+	return 0
 }
 
 function aws_login() {
